name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: sudo apt-get install libevent-dev
    - name: make
      run: make
    -name: install lib + hdrs
      run: sudo make install
    - name: examples
      run: make -C examples
